### ISSUE TITLE
change the entire panel, from EN language, to IT language 

### ISSUE THREAD

**Issue by Tonenz16** [INUI-Dev/IPTV-Panel#8]
Hello! first of all you have created a masterpiece, there are certain problems that I am experiencing, both I can not edit all the pages in Italian and without translation, I have modified the files.tpl, without having results. 
also I would like to know why when a user expires still manages to VIEW the VODs?

**Comment by LiamKenyon** [comment]
I did create this panel it was nulled from a now defunct site that no longer trades.

**Comment by Tonenz16** [comment]
it works for me, I can't see the credits in the reseller panel or even deduct them

**Comment by LiamKenyon** [comment]
I think you misunderstood.

I didn’t create the panel. The software isn’t supported so any changes etc… and how you use it etc… is up to you.

it’s only there to be downloaded

**Comment by Tonenz16** [comment]
have you tried? does it work for you?

**Comment by Tonenz16** [comment]
in panel/code/ returns me the problem: fatal error call to the function not indicated db_query
basically when a reseller and creates the line tells me column URL can not be null and consequently does not deduct credits

**Comment by LiamKenyon** [comment]
I’ve not used or tested the panel since it was first uploaded. It was tested and confirmed to be working multiple times by people.

**Comment by Tonenz16** [comment]
in fact it works 100% the only problem is that it does not deduct credits to resellers
