### ISSUE TITLE
the panel works but... 

### ISSUE THREAD

**Issue by Tonenz16** [INUI-Dev/IPTV-Panel#9]
hello, the panel works me 100%, the only thing I can not understand is why when a reseller creates a line does not deduct credits.

**Comment by Tonenz16** [comment]
if it works for you, maybe give me some advice? it's the only problem I'm having. Thank you!

**Comment by LC-iSaucyy** [comment]
> if it works for you, maybe give me some advice? it's the only problem I'm having. Thank you!

Hello, can you give me the commands to install it.
Please and Thank You.

**Comment by LiamKenyon** [comment]
Upload the files to hosting.

browse to the folder/install.php
